# Generated by Django 4.0.1 on 2022-01-21 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('HP', models.PositiveIntegerField(default=5)),
                ('RP', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('EQ', 'Equipment'), ('TR', 'Vendor trash'), ('CM', 'Consumable')], default='TR', max_length=2)),
                ('unique', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='HP',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='RP',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_size',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='game.character')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_item', to='game.item')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyLoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy', to='game.item')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_item', to='game.item')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='player_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.playerclass'),
        ),
    ]
