# Generated by Django 4.0.1 on 2022-01-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerinventory',
            unique_together={('item_id', 'character_id')},
        ),
    ]
