# Generated by Django 4.0.1 on 2022-01-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_playerinventory_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enemyloot',
            options={'ordering': ['enemy_id'], 'verbose_name_plural': 'Enemy Loot'},
        ),
        migrations.AlterModelOptions(
            name='playerinventory',
            options={'ordering': ['character_id'], 'verbose_name_plural': 'Player Inventories'},
        ),
        migrations.AlterUniqueTogether(
            name='enemyloot',
            unique_together={('item_id', 'enemy_id')},
        ),
    ]
