# Generated by Django 4.0.1 on 2022-01-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_enemyloot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinventory',
            options={'ordering': ['character'], 'verbose_name_plural': 'Player Inventories'},
        ),
        migrations.RenameField(
            model_name='playerinventory',
            old_name='character_id',
            new_name='character',
        ),
        migrations.AlterUniqueTogether(
            name='playerinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playerinventory',
            name='items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_items', to='game.item'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='playerinventory',
            name='item_id',
        ),
    ]
