# Generated by Django 4.0.1 on 2022-01-24 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_playerinventory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinventory',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_items', to='game.character'),
        ),
    ]
