# Generated by Django 4.0.1 on 2022-01-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_items_playerinventory_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinventory',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='game.character'),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.item'),
        ),
    ]
