# Generated by Django 4.0.1 on 2022-01-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_playerinventory_character_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinventory',
            options={'verbose_name_plural': 'Player Inventories'},
        ),
        migrations.RemoveField(
            model_name='playerinventory',
            name='character',
        ),
        migrations.AddField(
            model_name='playerinventory',
            name='character',
            field=models.ManyToManyField(to='game.Character'),
        ),
        migrations.RemoveField(
            model_name='playerinventory',
            name='item',
        ),
        migrations.AddField(
            model_name='playerinventory',
            name='item',
            field=models.ManyToManyField(to='game.Item'),
        ),
    ]
