# Generated by Django 4.0.1 on 2022-01-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_enemyloot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(to='game.Item'),
        ),
    ]
