# Generated by Django 4.0.1 on 2022-01-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_character_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinventory',
            name='character',
        ),
        migrations.RemoveField(
            model_name='playerinventory',
            name='item',
        ),
        migrations.AddField(
            model_name='enemy',
            name='loot',
            field=models.ManyToManyField(to='game.Item'),
        ),
        migrations.DeleteModel(
            name='EnemyLoot',
        ),
        migrations.DeleteModel(
            name='PlayerInventory',
        ),
    ]
